#!/bin/bash

# Create function to run this script
initdemo() {
  source "$JHOME/initdemo"
}

do_keep() {
  cd "$JHOME/playground"
}

do_reset() {
  cd "$JHOME"
  /bin/rm -rf playground
  /bin/mkdir -p playground && cd playground
}

do_usage() {
  cat <<EOFEOF
Usage: $progname OPTIONS

OPTIONS
 -h, --help      Display this help
 -r, --reset     Reset and CD to playground
 -k, --keep      CD to playground only
EOFEOF
}

TEMP=$(/usr/bin/getopt -n "$mycmd" -o hk   \
                       --long "help,keep" \
                       -- "$@") || exit $?

action=do_reset
eval set -- "$TEMP"
while true; do
  case "$1" in
    -h|--help) action=do_usage; shift 1;;
    -k|--keep) action=do_keep; shift 1;;
    -r|--reset) action=do_reset; shift 1;;
    --) shift 1; break;;
    *) echo "$cmd: Invalid option: $1" 1>&2; usage; echo; exit 1;;
  esac
done


if [ -z "$JHOME" ] ; then
  JHOME="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"
  progname="$(basename "${BASH_SOURCE[0]}")"
fi

$action
